// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXuEFAoa5t1p_pUiGW7yG83vcYI1pqPc',
    appId: '1:841448863795:web:cc68637d3be8cf342a0b46',
    messagingSenderId: '841448863795',
    projectId: 'bargain-aa76f',
    authDomain: 'bargain-aa76f.firebaseapp.com',
    storageBucket: 'bargain-aa76f.appspot.com',
    measurementId: 'G-D2H2L96BLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SOjOOZq2SNZX-oLitF4ZYYlJIOQEV74',
    appId: '1:841448863795:android:9b7a1262863746bc2a0b46',
    messagingSenderId: '841448863795',
    projectId: 'bargain-aa76f',
    storageBucket: 'bargain-aa76f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wU84avzckZ7GVxw1Rzp_2mK7mi-KTZ8',
    appId: '1:841448863795:ios:5e9c368b40d2f58b2a0b46',
    messagingSenderId: '841448863795',
    projectId: 'bargain-aa76f',
    storageBucket: 'bargain-aa76f.appspot.com',
    iosBundleId: 'com.example.bargain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5wU84avzckZ7GVxw1Rzp_2mK7mi-KTZ8',
    appId: '1:841448863795:ios:5e9c368b40d2f58b2a0b46',
    messagingSenderId: '841448863795',
    projectId: 'bargain-aa76f',
    storageBucket: 'bargain-aa76f.appspot.com',
    iosBundleId: 'com.example.bargain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXuEFAoa5t1p_pUiGW7yG83vcYI1pqPc',
    appId: '1:841448863795:web:34198a1c9fb596a02a0b46',
    messagingSenderId: '841448863795',
    projectId: 'bargain-aa76f',
    authDomain: 'bargain-aa76f.firebaseapp.com',
    storageBucket: 'bargain-aa76f.appspot.com',
    measurementId: 'G-JG4NQSDWKG',
  );

}
